package com.example.apartment_predictor.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;

import java.time.LocalDate;
import java.util.UUID;

@Entity
public class Review {

    //1. ATRIBUTES (FIELDS)
    @Id
    private String id;
    private String title;
    private String content;
    private int rating;
    private LocalDate reviewDate;
    // add apartment to Review class (because in UML Apartment-Review are related// have relationship).
    @ManyToOne
    private Apartment apartment;
    //private String reviewerId;

    //2. CONSTRUCTOR
    // 2.1 default constructor
    public Review() {
        // add id inside empty constructor because we want that
        // the id to be generated by the backend (java, springboot), not by the user
        this.id = UUID.randomUUID().toString();
    }

    // 2.2 Constructor with all fields (except reviewDate)
    public Review(String title, String content, int rating) {

        // add id inside empty constructor because we want that
        // the id to be generated by the backend (java, springboot), not by the user
        this.id = UUID.randomUUID().toString();
        this.title = title;
        this.content = content;
        this.rating = rating;
    }

    // 2.2 Constructor with all fields (include reviewDate)
    public Review(String title, String content, int rating, LocalDate reviewDate) {

        // add id inside empty constructor because we want that
        // the id to be generated by the backend (java, springboot), not by the user
        this.id = UUID.randomUUID().toString();
        this.title = title;
        this.content = content;
        this.rating = rating;
        this.reviewDate = reviewDate;
    }

    // 3. Getters & setters
    public String getId() {
        return id;
    }

    /*public void setId(String id) {
        this.id = id;
    }*/

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public LocalDate getReviewDate() {
        return reviewDate;
    }

    public void setReviewDate(LocalDate reviewDate) {
        this.reviewDate = reviewDate;
    }

    public Apartment getApartment() { return apartment; }

    public void setApartment(Apartment apartment) { this.apartment = apartment; }

    // 4. method toString
    @Override
    public String toString() {
        return "Review { " +
                "id: " + id +
                ", title: " + title +
                ", content: " + content +
                ", rating: " + rating +
                ", reviewDate: " + reviewDate +
                "}" ;
    }
}
